# Generated by Django 4.1.1 on 2022-10-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.medic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.patient')),
            ],
        ),
    ]
