# Generated by Django 4.1.1 on 2022-10-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_medicpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='historic',
        ),
    ]
