# Generated by Django 4.1.1 on 2022-10-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_remove_clinichistory_nuse_remove_suggestions_medic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='health_benefits',
            field=models.CharField(default='', max_length=80, verbose_name='Benfits'),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='health_risks',
            field=models.CharField(default='', max_length=80, verbose_name='Risks'),
        ),
    ]
